POST http://localhost:8080/v1/product/register
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MSIsImF1dGgiOiJTRUxMRVIiLCJpYXQiOjE3MDI4MTM4NTcsImV4cCI6MTcwMjgxNTY1N30.phWs6KlpH2bYDtnEX_Fka9LVQWBxLdOCtt6e1Xn8UFk

{
  "name": "상품명1",
  "category": "카테고리명",
  "price": 100,
  "description": "상품에 대한 설명입니다.",
  "origin": "원산지는 적어도 되고 안해도됩니다.",
  "discount": "FOR_SALE",
  "optionFormList": [
    {
      "count": 1,
      "optionName": "275"
    }
  ],
  "tagList": [
    {
      "tagName": "나이키"
    },
    {
      "tagName": "에어맥스"
    }
  ]
}