### 관리자 상품 요청 내역 보기
GET http://localhost:8080/admin/product/waitingList
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MiIsImF1dGgiOiJBRE1JTiIsImlhdCI6MTcwMjgxNDAyMCwiZXhwIjoxNzAyODE1ODIwfQ.Iw9Lkrd1gTd-l8FbSMeOMQ1UZDnvKE2-r9Dw4ArIMJY

### 관리자 요청 승인 거절
POST http://localhost:8080/admin/product/process
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MiIsImF1dGgiOiJBRE1JTiIsImlhdCI6MTcwMjgxNDAyMCwiZXhwIjoxNzAyODE1ODIwfQ.Iw9Lkrd1gTd-l8FbSMeOMQ1UZDnvKE2-r9Dw4ArIMJY

{
  "productId": 1,
  "confirm": "NOT_APPROVED",
  "reason": ""
}
